version: '3.8'

services:

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: no
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse  # Persistencia de datos
      - clickhouse_logs:/var/log/clickhouse-server  # Persistencia de logs
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
    environment:
      - CLICKHOUSE_DB=default  # Base de datos por defecto
      - CLICKHOUSE_USER=default  # Usuario por defecto
      - CLICKHOUSE_PASSWORD=default_password  # Contraseña por defecto
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    networks:
      - eda_network

volumes:
  clickhouse_data:
  clickhouse_logs:

networks:
  eda_network:
    name: eda_network
