sak_profile:
  target: clickhouse
  outputs:
    clickhouse:
      type: clickhouse
      host: localhost
      port: 9000
      user: user
      password: userpassword
      database: adw02_stag
      schema: adw02_stag

